EPC_DATASET_PATH: "/inputs/EPC_data/all-domestic-certificates/"
EPC_TOY_PATH: "/inputs/EPC_data/all-domestic-certificates/domestic-W06000015-Cardiff/certificates.csv"

POSTCODE_PATH: "/inputs/ukpostcodes.csv"
WIMD_PATH: "/inputs/wimd_df.csv"

FIGURE_PATH: "/outputs/data/Wales/Figures/"
